apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: codefresh-cap-app-proxy
  namespace: codefresh
spec:
  ingressClassName: nginx
  rules:
  - host: a2ed251cd969649a0b7d7cd4a4f8c63f-ff444eb88565937f.elb.ap-southeast-2.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: cap-app-proxy
            port:
              number: 3017
        path: /app-proxy/
        pathType: Prefix
status:
  loadBalancer: {}
